apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ template "app.chart" . }}
    release: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ .Chart.Name }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      annotations:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        # Key Manager config
        - name: cloverscan-contract-registry
          image: {{ .Values.global.repository }}/{{ .Values.global.image }}:{{ .Values.global.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
          {{- range $name, $value := .Values.services }}
          - name: {{ $value.protocol | lower }}{{ $value.port }}to{{ $value.targetPort }}
            protocol: {{ $value.protocol }}
            containerPort: {{ $value.port }}
          {{- end }}
          livenessProbe:
            {{- .Values.livenessProbe | toYaml | nindent 12 }}
          readinessProbe:
            {{- .Values.readinessProbe | toYaml | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}
      hostNetwork: {{ .Values.hostNetwork }}
      dnsPolicy: {{ .Values.dnsPolicy}}
