apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ template "app.chart" . }}
    release: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}
  ports:
  {{- range $i, $value := .Values.services }}
  - name: {{ $value.protocol | lower }}{{ $value.port }}to{{ $value.targetPort }}
    protocol: "{{ $value.protocol }}"
    port: {{ $value.port }}
    targetPort: {{ $value.targetPort }}
  {{- end }}
