global:
  repository: clovernetwork
  tag: test
  image: cloverscan-contract-registry
  env: dev
  host: dev.cloverscan.io

replicaCount: 1
hostNetwork: false
dnsPolicy: ClusterFirst
imagePullPolicy: IfNotPresent

configMap:
  # gRPC
  GRPC_ADDRESS: "0.0.0.0:6565"
  GRPC_GO_LOG_SEVERITY_LEVEL: "ERROR"
  # PostgreSQL
  DATABASE_ADDRESS: "postgresql.cloverscan-system-services-{env}:5432"
  DATABASE_USER: "postgres"
  DATABASE_PASSWORD: "12345"
  DATABASE_DB: "extractor"
  # Apache Kafka
  KAFKA_ADDRESS: "kafka.cloverscan-system-services-{env}:9092"
  PROMETHEUS_ADDRESS: "0.0.0.0:7575"
  GENESIS_START:
    dev: "false"
    prod: "true"
    # Redis
  REDIS_ADDRESS: "redis-master.cloverscan-system-services-{env}:6379"
  REDIS_USER: ""
  REDIS_PASSWORD: "123456"

services:
  - protocol: TCP
    port: 6565
    targetPort: 6565
  - protocol: TCP
    port: 7575
    targetPort: 7575

livenessProbe:
  tcpSocket:
    port: 6565
  failureThreshold: 1
  initialDelaySeconds: 90
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 2
readinessProbe:
  tcpSocket:
    port: 6565
  failureThreshold: 1
  initialDelaySeconds: 15
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 2

metrics:
  enabled: true
  port: 7575
